# Generated by Django 3.2.8 on 2023-05-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privada', models.BooleanField()),
                ('senha', models.CharField(blank=True, max_length=20)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.user')),
            ],
        ),
    ]
