# Generated by Django 3.2.8 on 2023-05-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.user')),
            ],
        ),
    ]
