# Generated by Django 3.2.8 on 2023-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tabueleiro',
            field=models.CharField(default=[[' ', ' ', ' '], [' ', ' ', ' '], [' ', ' ', ' ']], max_length=200),
        ),
    ]
