# Generated by Django 3.2.8 on 2023-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_sala_tabueleiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tabueleiro',
        ),
        migrations.AddField(
            model_name='sala',
            name='tabuleiro',
            field=models.CharField(default={'tabuleiro': [[' ', ' ', ' '], [' ', ' ', ' '], [' ', ' ', ' ']]}, max_length=200),
        ),
    ]
