# Generated by Django 3.2.8 on 2023-05-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0004_auto_20230508_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='tabuleiro',
            field=models.JSONField(default={'tabuleiro': [[' ', ' ', ' '], [' ', ' ', ' '], [' ', ' ', ' ']]}),
        ),
    ]
