# Generated by Django 3.2.8 on 2023-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_alter_sala_tabuleiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('privada', models.BooleanField(default=False)),
                ('senha', models.CharField(blank=True, max_length=20)),
                ('tabuleiro', models.JSONField()),
                ('jogadores', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sala',
            name='dono',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
