# Generated by Django 3.2.8 on 2023-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0007_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='room',
            name='jogadores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tabuleiro',
            field=models.JSONField(default=[[' ', ' ', ' '], [' ', ' ', ' '], [' ', ' ', ' ']]),
        ),
    ]
