# Generated by Django 3.2.8 on 2023-05-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0008_auto_20230509_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='jogadores',
            field=models.JSONField(default=[]),
        ),
    ]
