# Generated by Django 3.2.8 on 2023-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0009_alter_room_jogadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rodada',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
