# Generated by Django 3.2.8 on 2023-05-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0010_room_rodada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rodada',
        ),
        migrations.AddField(
            model_name='room',
            name='turno',
            field=models.IntegerField(default=0),
        ),
    ]
