# Generated by Django 3.2.8 on 2023-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0012_alter_room_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vencedor',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='turno',
            field=models.IntegerField(default=0),
        ),
    ]
