# Generated by Django 3.2.8 on 2023-05-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('tictactoe', '0013_auto_20230511_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.user'),
        ),
    ]
